services:
  - type: background
    name: grid-trading-bot
    env: python
    runtime: python3.11
    buildCommand: ""
    startCommand: "./start.sh"
    envVars:
      - key: KUCOIN_API_KEY
        fromSecret: KUCOIN_API_KEY
      - key: KUCOIN_API_SECRET
        fromSecret: KUCOIN_API_SECRET
      - key: KUCOIN_API_PASSPHRASE
        fromSecret: KUCOIN_API_PASSPHRASE
      - key: TELEGRAM_TOKEN
        fromSecret: TELEGRAM_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromSecret: TELEGRAM_CHAT_ID
      - key: SYMBOL
        value: "BTC-USDT"
      - key: LEVERAGE
        value: "10"
      - key: GRID_SIZE
        value: "10"
      - key: ADJUST_INTERVAL_MIN
        value: "15"
      - key: STOP_LOSS
        value: "0.01"
      - key: TAKE_PROFIT
        value: "0.02"
      - key: BUDGET
        value: "1000"
      - key: DATA_DIR
        value: "/mnt/data"
      - key: SANDBOX
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"
